### ISSUE TITLE
Please add instructions on how to run a DAML app against daml-on-sawtooth

### ISSUE THREAD

**Issue by gaborh-da** [blockchaintp/daml-on-sawtooth#13]
Please add instructions on how to run a DAML application against daml-on-sawtooth e.g. with similar docs as there are on [DAML-on-Fabric](https://github.com/hacera/daml-on-fabric).
The most important informations would be for example the following:
- how one can either start with or deploy a DAR
- how one can use a startup / market setup scenario
- what the important ports are (Ledger API...)

**Comment by gaborh-da** [comment]
It would also be interesting to see an example how one can connect to daml-on-sawtooth with a Navigator.

**Comment by paulwizviz** [comment]
@gaborh-da we are looking into it. I had a look at DAML-on-Fabric do you want instruction in README or in some other form. We have instruction in README

**Comment by dasormeter** [comment]
@paulwizviz README is good -- instructions that are immediately visible from the main github landing page of the repo

**Comment by paulwizviz** [comment]
@dasormeter Thanks for your feedback will look at addressing it.

**Comment by paulwizviz** [comment]
@dasormeter sorry for the delay. We are in the middle of releasing a product. I'll get back to you as soon as that is over.

**Comment by paulwizviz** [comment]
Instruction to connect daml navigator to daml-on-sawtooth in PR #20 once reviewed, it'll be merge to master.

**Comment by paulwizviz** [comment]
Latest doc updated now.
