### ISSUE TITLE
Daml-on-Sawtooth-tracer/transactions

### ISSUE THREAD

**Issue by vasisiop** [blockchaintp/daml-on-sawtooth#40]
The transactions are appeared on Navigator. Moreover, opening Daml-on-Sawtooth-tracer/Events there are info but on Daml-on-Sawtooth-tracer/Transactions is totally empty. There is no info or any template.

**Comment by dasormeter** [comment]
@vasisiop can you please clarify which example or application you have attempted to run and how you are running sawtooth locally?  in other words, could you clarify the steps to reproduce the problem you are reporting?

**Comment by vasisiop** [comment]
> @vasisiop can you please clarify which example or application you have attempted to run and how you are running sawtooth locally? in other words, could you clarify the steps to reproduce the problem you are reporting?

I am using this example https://github.com/digital-asset/dazl-client/tree/master/samples/ping-pong
Steps:

cd .../daml-on-sawtooth
export ISOLATION_ID=my-local-build
bin/build.sh

cd .../daml-on-sawtooth
./docker/run.sh

(open other terminal) cd ...daml on sawtooth
daml ledger allocate-parties Alice Bob --host localhost --port 9000
daml ledger upload-dar --host localhost --port 9000 /mypath/.daml/dist/PingPong-1.0.0.dar
daml ledger navigator --host localhost --port 9000

cd /mypath/dazl-client/samples/ping-pong
pipenv run python3 pingpong/bots.py --url http://localhost:9000

**Comment by dasormeter** [comment]
@vasisiop please make sure you are using the matching version of DAML SDK to what sawtooth is currently built with

Before running the daml commands, set this environment variable
`export DAML_SDK_VERSION=0.13.41`

**Comment by scealiontach** [comment]
So the latest master version here is at DAML SDK 1.3.0. Recommend that you you try again with that version.

**Comment by vsiop** [comment]
> So the latest master version here is at DAML SDK 1.3.0. Recommend that you you try again with that version.

On the latest master version on step 6  "Inspecting daml-on-sawtooth transactions" there is no "router" option on file ../compose/daml-local.yaml like the previous version to change the port in order to inspect transactions.
