### ISSUE TITLE
pom missing

### ISSUE THREAD

**Issue by m-kashif** [blockchaintp/daml-on-sawtooth#72]
I am getting following warning when i am trying to install daml on sawtooth in ubuntu

The POM for com.blockchaintp:sawtooth-utils:jar:0.0.1 is missing, no dependency information available
The POM for com.blockchaintp:keymanager:jar:0.0.1 is missing, no dependency information available

 Failed to execute goal on project sawtooth-daml-common: Could not resolve dependencies for project daml-on-sawtooth:sawtooth-daml-common:jar:3.0: The following artifacts could not be resolved: com.blockchaintp:keymanager:jar:0.0.1, com.blockchaintp:sawtooth-utils:jar:0.0.1: Could not find artifact com.blockchaintp:keymanager:jar:0.0.1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

**Comment by scealiontach** [comment]
We've recently updated the build to move some items out into another package sawtooth-utils (also open source) which is housed on a our own public repository at the moment.  However we unfortunately have yet to update the build documentation to reflect that.  In the meantime, you can clone and build/install the project at https://github.com/blockchaintp/paralos-java  to get that jar.

I will also update here when the documentation is updated properly.

**Comment by scealiontach** [comment]
The build docs have now been updated, and should build properly independent of the other projects due to the reference to the public repository.
